### ISSUE TITLE
OpenFile / OpenWith Error

### ISSUE THREAD

**Issue by jakebresnehan** [khalillechelt/grunt-textfile#1]
Hey @kahlil,

Not sure if its on my end or the plugin. For some reason the default task throws an error when the task tries to open Sublime.

I have followed this post - http://www.sublimetext.com/docs/2/osx_command_line.html and I also have the set up 'subl' in my aliases. Is there anything I am missing?

![screen shot 2013-06-27 at 10 45 45 am](https://f.cloud.github.com/assets/227719/713293/f0b986d0-dec2-11e2-8f5d-7093aa070f30.png)

Great plugin!!

Cheers,
Jake

**Comment by khalillechelt** [comment]
Hi there and thanks.

Did you install the subl command like described on this site? http://www.sublimetext.com/docs/2/osx_command_line.html

**Comment by jakebresnehan** [comment]
Yeah...

I mentioned that in the second paragraph.

**Comment by khalillechelt** [comment]
Haha damn, totally glanced over that. 
Hmm that's weird. I did nothing else. Although I did not set up any aliases. When I tried to set an alias for the command `subl` and I tried to use that with the Grunt plugin it didn't work either. So maybe the aliases are not available to Grunt? I am not sure...

**Comment by jakebresnehan** [comment]
No worries :)

I'll keep digging around and if I end up fixing it I'll make sure I leave a
note on this issue.

**Comment by khalillechelt** [comment]
Great! Thanks!

**Comment by khalillechelt** [comment]
Great! Thanks!

Am 27.06.2013 um 11:35 schrieb Jake Bresnehan notifications@github.com:

> No worries :) 
> 
> I'll keep digging around and if I end up fixing it I'll make sure I leave a 
> note on this issue. 
>

**Comment by khalillechelt** [comment]
Hey @jakebresnehan did you find the problem? Definitely interested in why this doesn't work for you.

**Comment by jakebresnehan** [comment]
Unfortunately I haven't really had time to dig into it yet. If I work out the issue I'll let you know.

Cheers,
Jake

**Comment by khalillechelt** [comment]
@jakebresnehan 

Does the `subl` command work when you use it manually?

**Comment by jakebresnehan** [comment]
@kahlil sure does. Strange hey. I think it might be some underlying settings because I have set it up on my work computer.

**Comment by khalillechelt** [comment]
Is `~/bin` in your `$PATH`?

**Comment by khalillechelt** [comment]
There is also this: 

> If you have the MacPorts version of Python installed, then starting Sublime Text 2 via the subl will not work correctly. As a workaround, start Sublime Text 2 first via Finder, and then interact with it using subl.

from http://www.sublimetext.com/docs/2/osx_command_line.html

**Comment by khalillechelt** [comment]
Closing because this is oooooolllld. And there is nothing I can do from my side here.
